# Item lists taken from Maze Rats by Ben Milton:
# http://questingblog.com/maze-rats-now-available/

mr_item_list = [
    "Animal Scent",
    "Bear Trap",
    "Bedroll",
    "Caltrops",
    "Chain (10 ft.)",
    "Chalk",
    "Chisel",
    "Crowbar",
    "Fishing Net",
    "Glass Marbles",
    "Glue",
    "Grappling Hook",
    "Grease",
    "Hacksaw",
    "Hammer",
    "Hand Drill",
    "Horn",
    "Iron Spikes",
    "Iron Tongs",
    "Lantern and Oil (d6 usage die)",
    "Large Sack",
    "Lockpicks (d6 usage die)",
    "Manacles",
    "Medicine (d6 usage die)",
    "Metal File",
    "Rations (d6 usage die)",
    "Rope (50 ft.)",
    "Steel Wire",
    "Shovel",
    "Steel Mirror",
    "Ten Foot Pole",
    "Tinderbox (d6 usage die)",
    "Torch (d6 usage die)",
    "Vial of Acid",
    "Vial of Poison",
    "Waterskin (d6 usage die)",
    ]

physical_effect = [
    "Animating",
    "Attracting",
    "Binding",
    "Blossoming",
    "Consuming",
    "Creeping",
    "Crushing",
    "Diminishing",
    "Dividing",
    "Duplicating",
    "Enveloping",
    "Expanding",
    "Fusing",
    "Grasping",
    "Hastening",
    "Hindering",
    "Illuminating",
    "Imprisoning",
    "Levitating",
    "Opening",
    "Petrifying",
    "Phasing",
    "Piercing",
    "Pursuing",
    "Reflecting",
    "Regenerating",
    "Rending",
    "Repelling",
    "Resurrecting",
    "Screaming",
    "Sealing",
    "Shapeshifting",
    "Shielding",
    "Spawning",
    "Transmuting",
    "Transporting",
    ]

physical_element = [
    "Acid",
    "Amber",
    "Bark",
    "Blood",
    "Bone",
    "Brine",
    "Clay",
    "Crow",
    "Crystal",
    "Ember",
    "Flesh",
    "Fungus",
    "Glass",
    "Honey",
    "Ice",
    "Insect",
    "Wood",
    "Lava",
    "Moss",
    "Obsidian",
    "Oil",
    "Poison",
    "Rat",
    "Salt",
    "Sand",
    "Sap",
    "Serpent",
    "Slime",
    "Stone",
    "Tar",
    "Thorn",
    "Vine",
    "Water",
    "Wine",
    "Wood",
    "Worm",
    ]

physical_form = [
    "Altar",
    "Armor",
    "Arrow ",
    "Beast",
    "Blade",
    "Cauldron",
    "Chain",
    "Chariot",
    "Claw",
    "Cloak",
    "Colossus",
    "Crown",
    "Elemental",
    "Eye",
    "Fountain",
    "Gate",
    "Golem",
    "Hammer",
    "Horn",
    "Key",
    "Mask",
    "Monolith",
    "Pit",
    "Prison",
    "Sentinel",
    "Servant",
    "Shield",
    "Spear",
    "Steed",
    "Swarm",
    "Tentacle",
    "Throne",
    "Torch",
    "Trap",
    "Wall",
    "Web",

]

ethereal_effect = [
    "Avenging",
    "Banishing",
    "Bewildering",
    "Blinding",
    "Charming",
    "Communicating",
    "Compelling",
    "Concealing",
    "Deafening",
    "Deceiving",
    "Deciphering",
    "Disguising",
    "Dispelling",
    "Emboldening",
    "Encoding",
    "Energizing",
    "Enlightening",
    "Enraging",
    "Excruciating",
    "Foreseeing",
    "Intoxicating",
    "Maddening",
    "Mesmerizing",
    "Mindreading",
    "Nullifying",
    "Paralyzing",
    "Revealing",
    "Revolting",
    "Scrying",
    "Silencing",
    "Soothing",
    "Summoning",
    "Terrifying",
    "Warding",
    "Wearying",
    "Withering",
]

ethereal_element = [
    "Ash",
    "Chaos",
    "Distortion",
    "Dream",
    "Dust",
    "Echo",
    "Ectoplasm",
    "Fire",
    "Fog",
    "Ghost",
    "Harmony",
    "Heat",
    "Light",
    "Lightning",
    "Memory",
    "Mind",
    "Mutation",
    "Negation",
    "Plague",
    "Plasma",
    "Probability",
    "Rain",
    "Rot",
    "Shadow",
    "Smoke",
    "Snow",
    "Soul",
    "Star",
    "Stasis",
    "Steam",
    "Thunder",
    "Time",
    "Void",
    "Warp",
    "Whisper",
    "Wind",
]

ethereal_form = [
    "Aura",
    "Beacon",
    "Beam",
    "Blast",
    "Blob",
    "Bolt",
    "Bubble",
    "Call",
    "Cascade",
    "Circle",
    "Cloud",
    "Coil",
    "Cone ",
    "Cube",
    "Dance",
    "Disk",
    "Field",
    "Form",
    "Gaze",
    "Loop",
    "Moment",
    "Nexus",
    "Portal",
    "Pulse",
    "Pyramid",
    "Ray",
    "Shard",
    "Sphere",
    "Spray",
    "Storm",
    "Swarm",
    "Torrent",
    "Touch",
    "Vortex",
    "Wave",
    "Word",
]
