# List of male and female names was taken from:
# http://www.random-generator.com/index.php?title=Victorian_Names

# "Weird names" were generated from:
# 

male_names = [
                "Aaron",
                "Abraham",
                "Adelbert",
                "Adoniram",
                "Alan",
                "Albert",
                "Alexander",
                "Alfred",
                "Algernon",
                "Algie",
                "Alistair",
                "Allen",
                "Aloysius",
                "Alphonse",
                "Alton",
                "Alvin",
                "Ambrose",
                "Andrew",
                "Anson",
                "Anthony",
                "Arch",
                "Archibald",
                "Archie",
                "Arlington",
                "Arnold",
                "Arthur",
                "Ashby",
                "Atherton",
                "Aubrey",
                "August",
                "Augustus",
                "Aylsworth",
                "Barnabas",
                "Barnaby",
                "Barney",
                "Bart",
                "Bartholomew",
                "Bascomb",
                "Bedford",
                "Benedict",
                "Benjamin",
                "Bennet",
                "Bentley",
                "Bernard",
                "Bert",
                "Bertram",
                "Bill",
                "Billy",
                "Bob",
                "Bradley",
                "Bramwell",
                "Buford",
                "Byron",
                "Calvin",
                "Carl",
                "Cecil",
                "Charles",
                "Charlie",
                "Chauncey",
                "Chesley",
                "Christopher",
                "Clarence",
                "Claude",
                "Clem",
                "Clement",
                "Clifford",
                "Clint",
                "Clinton",
                "Clovis",
                "Clyde",
                "Columbus",
                "Cornelius",
                "Cyril",
                "Cyrus",
                "Dan",
                "Daniel",
                "Daute",
                "David",
                "Delbert",
                "Delmar",
                "Dempsey",
                "Desmond",
                "Dexter",
                "Dick",
                "Dillard",
                "Donald",
                "Douglas",
                "Drew",
                "Drufus",
                "Dudley",
                "Eben",
                "Ebenezer",
                "Edbert",
                "Edgar",
                "Edmund",
                "Edson",
                "Edward",
                "Edwin",
                "Egbert",
                "Eldridge",
                "Elick",
                "Ellis",
                "Elmer",
                "Emerson",
                "Emmett",
                "Emory",
                "Ernest",
                "Eugene",
                "Fletcher",
                "Foster",
                "Frampton",
                "Francis",
                "Frank",
                "Franklin",
                "Fred",
                "Frederick",
                "Gabe",
                "Gabriel",
                "Gard",
                "Garrett",
                "Garth",
                "Gaylord",
                "Geoffrey",
                "George",
                "Gerald",
                "Gil",
                "Gilbert",
                "Godfrey",
                "Godric",
                "Gordon",
                "Grady",
                "Graham",
                "Gregory",
                "Guilford",
                "Gus",
                "Halsey",
                "Hamilton",
                "Hank",
                "Harcourt",
                "Harland",
                "Harley",
                "Harold",
                "Harris",
                "Harrison",
                "Harry",
                "Harvey",
                "Haskel",
                "Hayes",
                "Hector",
                "Henry",
                "Herbert",
                "Herman",
                "Hiram",
                "Hobart",
                "Horace",
                "Horatio",
                "Howard",
                "Hubert",
                "Hugh",
                "Humphrey",
                "Ichabod",
                "Irwin",
                "Isaac",
                "Jack",
                "Jacob",
                "James",
                "Jarrett",
                "Jarvis",
                "Jasper",
                "Jefferson",
                "Jeremy",
                "Jesse",
                "Jim",
                "John",
                "Jonathan",
                "Joseph",
                "Joshua",
                "Julian",
                "Justice",
                "Lafayette",
                "Larkin",
                "Larry",
                "Lawrence",
                "Lawson",
                "Leander",
                "Lee",
                "Leo",
                "Les",
                "Leslie",
                "Lester",
                "Lestor",
                "Levi",
                "Lew",
                "Lewis",
                "Lionel",
                "Louis",
                "Lowell",
                "Lucas",
                "Lucian",
                "Lucien",
                "Lucius",
                "Luke",
                "Luther",
                "Lyle",
                "Lysander",
                "Manfred",
                "Marcellus",
                "Marian",
                "Mark",
                "Martin",
                "Matthew",
                "Maurice",
                "Maxwell",
                "Maynard",
                "Meriwether",
                "Merrill",
                "Merritt",
                "Michael",
                "Milburn",
                "Milford",
                "Millard",
                "Montgomery",
                "Morgan",
                "Morris",
                "Mortimer",
                "Nat",
                "Nate",
                "Nathan",
                "Nathaniel",
                "Ned",
                "Nelson",
                "Nestor",
                "Neville",
                "Newton",
                "Nicholas",
                "Nigel",
                "Norbert",
                "Norman",
                "Norris",
                "Norval",
                "Oakley",
                "Octavian",
                "Octavius",
                "Ora",
                "Oral",
                "Orson",
                "Orville",
                "Oscar",
                "Osgood",
                "Owen",
                "Parley",
                "Pat",
                "Patrick",
                "Paul",
                "Percival",
                "Perry",
                "Peter",
                "Philander",
                "Philbert",
                "Philip",
                "Phineas",
                "Pierce",
                "Porter",
                "Prestor",
                "Quinby",
                "Ralph",
                "Randolph",
                "Ransom",
                "Raymond",
                "Redmond",
                "Reginald",
                "Reynard",
                "Richard",
                "Robert",
                "Roderick",
                "Rodney",
                "Roger",
                "Ronald",
                "Rowland",
                "Roy",
                "Royden",
                "Rudolph",
                "Rufus",
                "Rupert",
                "Rush",
                "Samuel",
                "Sanders",
                "Seymour",
                "Simon",
                "Stan",
                "Stanley",
                "Stephen",
                "Stewart",
                "Stuart",
                "Sumner",
                "Sydney",
                "Sylvester",
                "Ted",
                "Thaddeus",
                "Theodore",
                "Theron",
                "Thomas",
                "Thurman",
                "Tilden",
                "Tim",
                "Timothy",
                "Titus",
                "Tom",
                "Ulysses",
                "Unwin",
                "Valentine",
                "Vernon",
                "Victor",
                "Vincent",
                "Vivian",
                "Wallace",
                "Walt",
                "Walter",
                "Warren",
                "Wendell",
                "Wesley",
                "Wilbur",
                "Wilford",
                "Wilfred",
                "Will",
                "William",
                "Wilson",
                "Winston",
                "Winthrop",
                "Wyatt",
                "Wylie",
                "Xavier",
                "Zachary",
                ]

female_names = [
                "Abigail",
                "Ada",
                "Adah",
                "Adelaide",
                "Adele",
                "Adeline",
                "Adella",
                "Adrianna",
                "Agatha",
                "Agnes",
                "Alice",
                "Allie",
                "Alma",
                "Almira",
                "Almyra",
                "Alta",
                "Althea",
                "Alva",
                "Amalia",
                "Amanda",
                "Amarantha",
                "Amaryllis",
                "Amelia",
                "Amethyst",
                "Amy",
                "Anastasia",
                "Ann",
                "Anna",
                "Annabel",
                "Anne",
                "Annie",
                "Anthea",
                "April",
                "Arabella",
                "Arah",
                "Araminta",
                "Ariel",
                "Audra",
                "Audrey",
                "Augusta",
                "Augustina",
                "Aurelia",
                "Ava",
                "Axa",
                "Beatrice",
                "Becky",
                "Belle",
                "Bernice",
                "Bertha",
                "Bertilda",
                "Beryl",
                "Bess",
                "Bessie",
                "Beth",
                "Bethany",
                "Betsy",
                "Betty",
                "Blanche",
                "Caledonia",
                "Calla",
                "Caroline",
                "Carrie",
                "Catherine",
                "Cecilia",
                "Celia",
                "Charity",
                "Charlotta",
                "Charlotte",
                "Chastity",
                "Chloe",
                "Claire",
                "Clara",
                "Clementine",
                "Clotilde",
                "Columbia",
                "Constance",
                "Cora",
                "Coral",
                "Cordelia",
                "Cornelia",
                "Cynthia",
                "Daisy",
                "Deborah",
                "Delphia",
                "Delphine",
                "Delphinia",
                "Delphinium",
                "Diana",
                "Diane",
                "Dinah",
                "Docia",
                "Dolly",
                "Dora",
                "Dorcas",
                "Doris",
                "Dorothy",
                "Dot",
                "Dove",
                "Drisella",
                "Drusilla",
                "Edith",
                "Edna",
                "Edwina",
                "Elaine",
                "Eleanor",
                "Eliza",
                "Elizabeth",
                "Ella",
                "Ellen",
                "Ellie",
                "Elmira",
                "Elnora",
                "Eloise",
                "Elsie",
                "Elvira",
                "Emerson",
                "Emilia",
                "Emily",
                "Emma",
                "Emmalina",
                "Ermalinde",
                "Ernestine",
                "Estella",
                "Estelle",
                "Esther",
                "Ethel",
                "Ettie",
                "Eudora",
                "Eugenia",
                "Eula",
                "Eunice",
                "Euphemia",
                "Euphrasia",
                "Eva",
                "Evangeline",
                "Fanny",
                "Fay",
                "Fern",
                "Fidelia",
                "Flora",
                "Florence",
                "Frances",
                "Garnet",
                "Geneva",
                "Genevieve",
                "Georgia",
                "Georgina",
                "Geraldine",
                "Gertie",
                "Gertrude",
                "Ginevra",
                "Ginny",
                "Gladys",
                "Grace",
                "Griselda",
                "Gwendolyn",
                "Hanna",
                "Hannah",
                "Harriet",
                "Hattie",
                "Hazel",
                "Helen",
                "Helene",
                "Henrietta",
                "Hermione",
                "Hester",
                "Hettie",
                "Hillary",
                "Honora",
                "Hope",
                "Hortencia",
                "Hortense",
                "Ida",
                "Imogene",
                "Iona",
                "Iphigenia",
                "Irene",
                "Iris",
                "Isabell",
                "Isabella",
                "Ivy",
                "Jane",
                "Jemima",
                "Jennie",
                "Jennifer",
                "Jenny",
                "Jessamine",
                "Jessica",
                "Jessie",
                "Jill",
                "Josephine",
                "Judith",
                "Julia",
                "Juliet",
                "Kate",
                "Katherine",
                "Kit",
                "Kitty",
                "Laura",
                "Laurinda",
                "Lavinia",
                "Leah",
                "Lela",
                "Lena",
                "Lenora",
                "Leola",
                "Leslie",
                "Letitia",
                "Lila",
                "Lilian",
                "Lillian",
                "Lillie",
                "Lilly",
                "Lily",
                "Livilla",
                "Liza",
                "Lizzy",
                "Lorena",
                "Lorraine",
                "Lottie",
                "Louisa",
                "Louise",
                "Love",
                "Lucie",
                "Lucille",
                "Lucinda",
                "Lucretia",
                "Lucy",
                "Luella",
                "Lula",
                "Lulu",
                "Lura",
                "Lyda",
                "Lydia",
                "Lyle",
                "Mabel",
                "Madeline",
                "Magnolia",
                "Margaret",
                "Maria",
                "Marie",
                "Marion",
                "Martha",
                "Mary",
                "Matilda",
                "Mattie",
                "Maud",
                "Maude",
                "Maxie",
                "Maxine",
                "May",
                "Maisie",
                "Mercy",
                "Messalina",
                "Mildred",
                "Millicent",
                "Mina",
                "Minerva",
                "Minnie",
                "Miranda",
                "Miriam",
                "Molly",
                "Muriel",
                "Myrtle",
                "Nancy",
                "Naomi",
                "Natalie",
                "Nell",
                "Nellie",
                "Nelly",
                "Netta",
                "Nettie",
                "Neva",
                "Nicola",
                "Nicole",
                "Nola",
                "Nora",
                "Norah",
                "Novella",
                "Octavia",
                "Odessa",
                "Olive",
                "Olivia",
                "Ophelia",
                "Ora",
                "Orpha",
                "Palma",
                "Pamela",
                "Pansy",
                "Parthenia",
                "Pat",
                "Patience",
                "Patricia",
                "Patsy",
                "Pearl",
                "Pearla",
                "Peggy",
                "Penelope",
                "Permilia",
                "Persephone",
                "Petunia",
                "Philippa",
                "Philomena",
                "Phoebe",
                "Polly",
                "Pollyanna",
                "Portia",
                "Preshea",
                "Priscilla",
                "Prudence",
                "Prunella",
                "Rachel",
                "Rebecca",
                "Rhoda",
                "Rhody",
                "Roberta",
                "Rosa",
                "Rosalie",
                "Rosalind",
                "Rosamund",
                "Rose",
                "Rosemary",
                "Rosetta",
                "Rowena",
                "Rufina",
                "Ruth",
                "Sally",
                "Samantha",
                "Sarah",
                "Savannah",
                "Selina",
                "Selma",
                "Sharon",
                "Silvia",
                "Sophia",
                "Sophie",
                "Sophronia",
                "Sophy",
                "Stella",
                "Sudie",
                "Susan",
                "Susanna",
                "Sylvia",
                "Tabitha",
                "Temperance",
                "Thelma",
                "Theodora",
                "Theodosia",
                "Theresa",
                "Thomasina",
                "Thora",
                "Timothea",
                "Tulip",
                "Ursula",
                "Valencia",
                "Valerie",
                "Vallie",
                "Vera",
                "Verd",
                "Verona",
                "Vertiline",
                "Vesta",
                "Victoria",
                "Vinetta",
                "Viola",
                "Violet",
                "Virginia",
                "Vivian",
                "Wilhelmina",
                "Winifred",
                "Winnie",
                "Winnifred",
                "Zelda",
                "Zella",
                "Zylphia",
                ]

weird_names = [
                "Cobra Paw",
                "Organoamphibian",
                "Ember Rush",
                "Ethereal Cut",
                "Falcon Trap",
                "Feline Raven",
                "Floroedge",
                "Frost Shine",
                "Microbee",
                "Microhatchet",
                "Photoserpent",
                "Raptor Rapier",
                "Rush Caster",
                "Shadow Stinger",
                "Siege Piercer",
                "Slicing Tornado",
                "Spear Cat",
                "Temporal Gloom",
                "Tempusgloom",
                "Vibrotronic",
                "Ambush Dog",
                "Astral Sham",
                "Bomb Killer",
                "Computer Cancellor",
                "Cosmic Spike",
                "Death Bolt",
                "Diviner Blizzard",
                "Ethereal Falcon",
                "Fever Glare",
                "Girl Shield",
                "Glare Seeker",
                "Insect Finder",
                "Metal Trap",
                "Tarantula",
                "Orange Gal",
                "Pearl Beast",
                "Scimtar Howl",
                "Screaming Rush",
                "Sorcery Plastique",
                "Web Gut",
                "Aquaticoid",
                "Atomisoul",
                "Brain Chance",
                "Disease Hack",
                "Eagle Edge",
                "Eat Blast",
                "Ember Blizzard",
                "Enchantmentborg",
                "God Warrior",
                "Hunter Detonator",
                "Raptor Star",
                "River Count",
                "Royal Oracle",
                "Ruby Chill",
                "Rubyo",
                "Snow Ray",
                "Spider Cat",
                "Spider Giggle",
                "Trap Butterfly",
                "Whale Viper",
                "Aeroemper",
                "Assault Net",
                "Brain Nemesis",
                "Charm Wolf",
                "Dynatalon",
                "Forgery Lass",
                "High Star",
                "Hour Zephyr",
                "Murkthorn",
                "Noble Construct",
                "Obsidian Burner",
                "Ruby Axe",
                "Sickness Time",
                "Snow Club",
                "Spirit Blazer",
                "Superior Caster",
                "Swim Comet",
                "Swimmer Tempest",
                "Tornado Foot",
                "Toxic Leaf",
                "Arrowsting",
                "Cleric Master",
                "Conjurer Mentalist",
                "Conjuress Plague",
                "Crimson Fire",
                "Gal Stabber",
                "Hunter Priest",
                "Lake Bullet",
                "Lightning Killer",
                "Mirage Eagle",
                "Night Mage",
                "Null Tornado",
                "Orange Serpent",
                "Rose Lie",
                "Seed Draft",
                "Sound Breed",
                "Spider Lynx",
                "Stab Crusher",
                "Swim Bee",
                "Vibrocount",
                "Chainsaw VHS",
                ]
