# Trait lists taken from Maze Rats by Ben Milton:
# http://questingblog.com/maze-rats-now-available/

physical_description_list = [
    "Aquiline",
    "Athletic",
    "Barrel-Chested",
    "Boney",
    "Brawny",
    "Brutish",
    "Bullnecked",
    "Chiseled",
    "Coltish",
    "Corpulent",
    "Craggy",
    "Delicate",
    "Furrowed",
    "Gaunt",
    "Gorgeous",
    "Grizzled",
    "Haggard",
    "Handsome",
    "Hideous",
    "Lanky",
    "Pudgy",
    "Ripped",
    "Rosy",
    "Scrawny",
    "Sinewy",
    "Slender",
    "Slumped",
    "Solid",
    "Square-Jawed",
    "Statuesque",
    "Towering",
    "Trim",
    "Weathered",
    "Willowy",
    "Wiry",
    "Wrinkled",
    ]

physical_detail_list = [
    "Acid scars",
    "Battle scars",
    "Birthmark",
    "Braided hair",
    "Brand mark",
    "Broken nose",
    "Bronze skinned",
    "Burn scars	",
    "Bushy eyebrows",
    "Curly hair",
    "Dark skinned",
    "Dreadlocks",
    "Exotic accent",
    "Flogging scars",
    "Freckles",
    "Gold tooth",
    "Hoarse voice",
    "Huge beard",
    "Long hair",
    "Matted hair",
    "Missing ear",
    "Missing teeth",
    "Moustache",
    "Muttonchops",
    "Nine fingers",
    "Oiled hair",
    "One-eyed",
    "Pale skinned",
    "Piercings	",
    "Ritual scars",
    "Sallow skin",
    "Shaved head",
    "Sunburned",
    "Tangled hair",
    "Tattoos",
    "Topknot",
    ]

background_list = [
    "Alchemist",
    "Beggar-prince",
    "Blackmailer",
    "Bounty-hunter",
    "Chimney sweep",
    "Coin-clipper",
    "Contortionist",
    "Counterfeiter",
    "Cultist",
    "Cutpurse",
    "Debt-collector",
    "Deserter",
    "Fence",
    "Fortuneteller",
    "Galley slave",
    "Gambler",
    "Gravedigger",
    "Headsman",
    "Hedge knight",
    "Highwayman",
    "Housebreaker",
    "Kidnapper",
    "Mad prophet",
    "Mountebank",
    "Peddler",
    "Pit-fighter",
    "Poisoner",
    "Rat-catcher",
    "Scrivener",
    "Sellsword",
    "Slave",
    "Smuggler",
    "Street performer",
    "Tattooist",
    "Urchin",
    "Usurer",
    ]

clothing_list = [
    "Antique",
    "Battle-torn",
    "Bedraggled",
    "Blood-stained",
    "Ceremonial",
    "Dated",
    "Decaying",
    "Eccentric",
    "Elegant",
    "Embroidered",
    "Exotic",
    "Fashionable",
    "Flamboyant",
    "Food-stained",
    "Formal",
    "Frayed",
    "Frumpy",
    "Garish",
    "Grimy",
    "Haute couture",
    "Lacey",
    "Livery",
    "Mud-stained",
    "Ostentatious",
    "Oversized",
    "Patched",
    "Patterned",
    "Perfumed",
    "Practical",
    "Rumpled",
    "Sigils",
    "Singed",
    "Tasteless",
    "Undersized",
    "Wine-stained",
    "Worn out",
    ]

personality_list = [
    "Bitter",
    "Brave",
    "Cautious",
    "Chipper",
    "Contrary",
    "Cowardly",
    "Cunning",
    "Driven",
    "Entitled",
    "Gregarious",
    "Grumpy",
    "Heartless",
    "Honor-bound",
    "Hotheaded",
    "Inquisitive",
    "Irascible",
    "Jolly",
    "Know-it-all",
    "Lazy",
    "Loyal",
    "Menacing",
    "Mopey",
    "Nervous",
    "Protective",
    "Righteous",
    "Rude",
    "Sarcastic",
    "Savage",
    "Scheming",
    "Serene",
    "Spacey",
    "Stoic",
    "Stubborn",
    "Stuck-up",
    "Suspicious",
    "Wisecracking",
    ]

mannerism_list = [
    "Anecdotes",
    "Breathy",
    "Chuckles",
    "Clipped",
    "Cryptic",
    "Deep voice",
    "Drawl",
    "Enunciates",
    "Flowery speech",
    "Gravelly voice",
    "Highly formal",
    "Hypnotic",
    "Interrupts",
    "Laconic",
    "Laughs",
    "Long pauses",
    "Melodious",
    "Monotone",
    "Mumbles",
    "Narrates",
    "Overly casual",
    "Quaint sayings",
    "Rambles",
    "Random facts",
    "Rapid-fire",
    "Rhyming",
    "Robotic",
    "Slow speech",
    "Speechifies",
    "Squeaky",
    "Street slang",
    "Stutters",
    "Talks to self",
    "Trails off",
    "Very loud",
    "Whispers",
    ]
